<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tt</string>
		<string>tt2</string>
		<string>html</string>
	</array>
	<key>firstLineMatch</key>
	<string>\[\%</string>
	<key>name</key>
	<string>TT2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[\%[-+=~]?#</string>
			<key>end</key>
			<string>[-+=~]?\%\]</string>
			<key>name</key>
			<string>comment.block.tt</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\%[-+=~]?(?!\#)\s*</string>
			<key>contentName</key>
			<string>source.tt.tag.content</string>
			<key>end</key>
			<string>\s*[-+=~]?\%\]</string>
			<key>name</key>
			<string>source.tt.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*?(?=[-+=~]?\%\]|$)</string>
					<key>name</key>
					<string>comment.number-sign.tt</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?\d+(\.\d+)?</string>
					<key>name</key>
					<string>constant.numeric.tt</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(template|component|error|loop|content)\b</string>
					<key>name</key>
					<string>variable.language.tt</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=DISABLED=\w+(\(.*?\))?(\.\w+(\(.*?\))?)+</string>
					<key>name</key>
					<string>variable.other.tt.dotop</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=DISABLED=\w+(\(.*?\))</string>
					<key>name</key>
					<string>variable.other.tt.args</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.tt</string>
					<key>swallow</key>
					<string>\\.</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.tt</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\$\w+</string>
							<key>name</key>
							<string>variable.other.tt.interpolated</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\$\{.*?\}</string>
							<key>name</key>
							<string>variable.other.tt.embedded</string>
						</dict>
					</array>
					<key>swallow</key>
					<string>\\.</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bGET|SET|CALL|DEFAULT\b</string>
					<key>name</key>
					<string>keyword.other.tt.variable</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.template</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(INCLUDE|PROCESS|INSERT|WRAPPER)\s+(\S+)</string>
					<key>name</key>
					<string>keyword.other.tt.template</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.plugin</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\bUSE\s+(\S+?)(?=\(|\s)</string>
					<key>name</key>
					<string>keyword.other.tt.plugin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMETA\b</string>
					<key>name</key>
					<string>keyword.other.tt.metadata</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTAGS\b</string>
					<key>name</key>
					<string>keyword.other.tt.input</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bDEBUG\b</string>
					<key>name</key>
					<string>keyword.other.tt.debug</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bCLEAR\b</string>
					<key>name</key>
					<string>keyword.other.tt.output</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bEND|STOP|RETURN\b</string>
					<key>name</key>
					<string>keyword.control.tt.flow</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.template</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\bBLOCK\s+(\S+)</string>
					<key>name</key>
					<string>keyword.control.tt.block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bFOR(EACH)?|WHILE|LAST|NEXT\b</string>
					<key>name</key>
					<string>keyword.control.tt.loop</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bIF|ELSIF|ELSE|UNLESS|SWITCH|CASE\b</string>
					<key>name</key>
					<string>keyword.control.tt.condition</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bTRY|CATCH|THROW|FINAL\b</string>
					<key>name</key>
					<string>keyword.control.tt.error</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.filter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\bFILTER\s+(\S+)</string>
					<key>name</key>
					<string>keyword.control.tt.filter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bMACRO\s+(\w+)\b</string>
					<key>name</key>
					<string>keyword.control.tt.macro</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(RAW_)?PERL\b</string>
					<key>name</key>
					<string>keyword.control.tt.perl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:AND|OR|NOT)\b</string>
					<key>name</key>
					<string>keyword.operator.tt.logical</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:IN)\b</string>
					<key>name</key>
					<string>keyword.operator.tt.misc</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tt2</string>
	<key>uuid</key>
	<string>E3556F15-3D09-4A14-AF77-7DBED0AEEA8E</string>
</dict>
</plist>
