<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tt</string>
		<string>tt3</string>
		<string>html</string>
		<string>css</string>
	</array>
	<key>firstLineMatch</key>
	<string>(\[|\%)\%</string>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\s*\}</string>
	<key>name</key>
	<string>TT3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[\%[-+=~]?#</string>
			<key>end</key>
			<string>[-+=~]?\%\]</string>
			<key>name</key>
			<string>comment.block.tt.tt3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[#</string>
			<key>end</key>
			<string>#\]</string>
			<key>name</key>
			<string>comment.block.tt</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\%[-+=~]?(?!\#)\s*</string>
			<key>contentName</key>
			<string>source.tt.tag.content</string>
			<key>end</key>
			<string>\s*[-+=~]?\%\]</string>
			<key>name</key>
			<string>source.tt.tag.inline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#syntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\%\%</string>
			<key>contentName</key>
			<string>source.tt.tag.content</string>
			<key>end</key>
			<string>\s*$</string>
			<key>name</key>
			<string>source.tt.tag.outline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#syntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\?[-+=~]?(?!\#)\s*</string>
			<key>contentName</key>
			<string>source.tt.tag.content</string>
			<key>end</key>
			<string>\s*[-+=~]?\?\]</string>
			<key>name</key>
			<string>source.tt.tag.control</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#syntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controls</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_commands</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(block|slot|sub)\s+(\S+)</string>
			<key>name</key>
			<string>keyword.control.tt.block</string>
		</dict>
		<key>branch_commands</key>
		<dict>
			<key>match</key>
			<string>\bif|elsif|else|unless|switch|case\b</string>
			<key>name</key>
			<string>keyword.control.tt.condition</string>
		</dict>
		<key>commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#branch_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#error_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flow_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plugin_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#template_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controls</string>
				</dict>
			</array>
		</dict>
		<key>controls</key>
		<dict>
			<key>match</key>
			<string>\bTAGS|COMMANDS|HTML_CMDS|META\b</string>
			<key>name</key>
			<string>keyword.other.tt.control</string>
		</dict>
		<key>double_quote</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.tt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$\w+</string>
					<key>name</key>
					<string>variable.other.tt3.interpolated</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$\{.*?\}</string>
					<key>name</key>
					<string>variable.other.tt3.embedded</string>
				</dict>
			</array>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<key>error_commands</key>
		<dict>
			<key>match</key>
			<string>\btry|catch|throw|final\b</string>
			<key>name</key>
			<string>keyword.control.tt.error</string>
		</dict>
		<key>flow_commands</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.fragment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(stop|return|end(#\w+)?)\b</string>
			<key>name</key>
			<string>keyword.control.tt.flow</string>
		</dict>
		<key>html_commands</key>
		<dict>
			<key>match</key>
			<string>\b(h1|h2|h3|h4|div|span|p|ul|li|a|b|i)\b</string>
			<key>name</key>
			<string>keyword.control.tt.html</string>
		</dict>
		<key>inline_comment</key>
		<dict>
			<key>match</key>
			<string>#.*?(?=[-+=~]?\%\]|$)</string>
			<key>name</key>
			<string>comment.number-sign.tt</string>
		</dict>
		<key>language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#syntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#commands</string>
				</dict>
			</array>
		</dict>
		<key>loop_commands</key>
		<dict>
			<key>match</key>
			<string>\bfor|while|next|last\b</string>
			<key>name</key>
			<string>keyword.control.tt.loop</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>-?\d+(\.\d+)?</string>
			<key>name</key>
			<string>constant.numeric.tt</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>\b(and|or|not|in)\b|\=&gt;|\-|\+|\/|\*|=|\.</string>
			<key>name</key>
			<string>keyword.operator.tt.operator</string>
		</dict>
		<key>plugin_commands</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.plugin</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\buse\s+(\S+?)(?=\(|\s)</string>
			<key>name</key>
			<string>keyword.other.tt.plugin</string>
		</dict>
		<key>reserved_var</key>
		<dict>
			<key>match</key>
			<string>\b(Page|Site|template|component|error|loop|content)\b</string>
			<key>name</key>
			<string>variable.language.tt.reserved</string>
		</dict>
		<key>single_quote</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.tt</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<key>syntax</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double_quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reserved_var</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_quote</string>
				</dict>
			</array>
		</dict>
		<key>template_commands</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.template</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(fill|into)\s+(\S+(\s*\+\s*\S+)*)</string>
			<key>name</key>
			<string>keyword.other.tt.template</string>
		</dict>
		<key>variable_commands</key>
		<dict>
			<key>match</key>
			<string>\b(is|as|with|just)\b</string>
			<key>name</key>
			<string>keyword.other.tt.variable</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tt3</string>
	<key>uuid</key>
	<string>AA2F3AAB-6C62-4392-B57F-ACFEC5A24D13</string>
</dict>
</plist>
